### ISSUE TITLE
new CosmosClient throws ERR_INVALID_URL

### ISSUE THREAD

**Issue by xuxife** [microsoft/azurechatgpt#44]
Hi, I'm using my fresh deployed cosmos db URI in a format of `"https://<my-cosmos>.documents.azure.com:443/"`, while the following runtime error is thrown.
I check the [@azure/cosmos document](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/quickstart-nodejs?tabs=azure-portal%2Cpasswordless%2Clinux%2Csign-in-azure-cli), turns out the URI format is correct.

Do we have any clue about the cause or have any workaround?

<img width="969" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/28257575/9caee361-df1e-4078-a4b4-75a09fa2260c">

```
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at ChatMenu (./features/chat/chat-menu/chat-menu.tsx:19:138)
    at stringify (<anonymous>)
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at Home (./app/chat/page.tsx:18:138)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at ChatMenu (./features/chat/chat-menu/chat-menu.tsx:19:138)
    at stringify (<anonymous>)
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at ChatMenu (./features/chat/chat-menu/chat-menu.tsx:19:138)
    at stringify (<anonymous>)
digest: "304417822"
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at Home (./app/chat/page.tsx:18:138)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at memoryContainer (./features/common/cosmos.ts:15:20)
    at FindAllChatThreadForCurrentUser (./features/chat/chat-services/chat-thread-service.ts:29:92)
    at ChatMenu (./features/chat/chat-menu/chat-menu.tsx:19:138)
    at stringify (<anonymous>)

```

**Comment by janegilring** [comment]
I am seeing a similar error which I think is related to Cosmos:

![image](https://github.com/microsoft/azurechatgpt/assets/2039662/fa73d866-f77b-456b-b29a-f3421f5b2585)

The Application setting is defined like this:

![image](https://github.com/microsoft/azurechatgpt/assets/2039662/518cbfb7-0855-455a-954e-ecc76116c058)

Do you see any obvious reason for why it is failing?

**Comment by oliverlabs** [comment]
@janegilring, today's commits broke the deployment by trying to fix the spelling error in this variable. It should be `AZURE_COSMOSDB_URI`. Revert your branch to the last of Aug 3 commit and redeploy the app. It worked for me.

**Comment by thivy** [comment]
Thanks @oliverlabs Yes that is correct, there were typo for cosmos related in env.local and fixed. 

It used to be COSMOSE and now fixed to COSMOS
